### PR TITLE
Feathers 3.x.x

### PR DESCRIPTION
**Pull request by DaviTeodoro**
Update the aplication to work with Feathers V3

### CODE REVIEW

**Comment by silvestreh** [comment]
Looks like you changed the `package.json` author section. I'm ok with turning it into an array of authors 😉

**Comment by DaviTeodoro** [comment]
I did not expect you would answer to this pull request. I was planing to continue the project by my self.

**Comment by pkej** [comment]
`"contributors":[
{ "name" : "Silvestre Herrera"
, "url" : "https://blog.feathersjs.com/ssr-vuejs-app-with-feathers-and-nuxt-bb7dfd3e6397/"
, "Description": "Original author"
},
{ "name" : "Davi Teodoro"
, "url" : "https://github.com/DaviTeodoro"
, "Description": "Feathers 3.0 upgrade"
}
]`

I believe that should be the main point

**Comment by pkej** [comment]
Works well Davi,
I took a look through the code, and hoping to find a way to fix (create-nuxt-app)[https://github.com/nuxt-community/create-nuxt-app]? which is great for setup of different apps, but uses the old feathers api. After working and working with finding out of some errors yesterday and today I decided to see if there were any PRs for @silvestreh's code, and lucky me.

As for your code, I found some other pretty clean code for doing the login/logout/register and ssr as well as client-side storage: (lewebsimple/feathers-nuxt)[https://github.com/lewebsimple/feathers-nuxt],
which I think would be pretty clean. However, I don't remember if it needs both a client and server process.

**Comment by pkej** [comment]
Ah, it used the old feathers api.

**Comment by pkej** [comment]
IIRC, it also triggered an error in Safari on Mac which had to be fixed with a polyfill.

**Comment by cameronblandford** [comment]
Any reasoning for why this hasn't been merged yet?

**Pull request closed without merging**
